"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Plus, RefreshCw } from "lucide-react";

type Item = Record<string, unknown>;
const endpoint: Record<string, string> = { inventory: "properties", clients: "leads", appointments: "appointments", offers: "offers", deals: "deals", commissions: "commissions" };
const labels: Record<string, string> = { inventory: "inmueble", clients: "cliente", appointments: "visita", offers: "oferta", deals: "operación", commissions: "regla de comisión" };

export function OperationsConsole({ section }: { section: string }) {
  const [items, setItems] = useState<Item[]>([]); const [properties, setProperties] = useState<Item[]>([]); const [leads, setLeads] = useState<Item[]>([]); const [owners, setOwners] = useState<Item[]>([]);
  const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(false); const api = endpoint[section];
  const load = async () => {
    if (!api) return; setLoading(true);
    const sources = await Promise.all([fetch(`/api/${api}`).then(r => r.json()), fetch("/api/properties").then(r => r.json()), fetch("/api/leads").then(r => r.json()), fetch("/api/owners").then(r => r.json())]);
    setItems(sources[0][api] ?? sources[0].properties ?? sources[0].rules ?? []); setProperties(sources[1].properties ?? []); setLeads(sources[2].leads ?? []); setOwners(sources[3].owners ?? []); setLoading(false);
  };
  useEffect(() => { load(); }, [section]);
  const send = async (path: string, data: Record<string, unknown>) => { const response = await fetch(path, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const body = await response.json(); setNotice(response.ok ? `${labels[section] ?? "Registro"} creado correctamente.` : body.error ?? "No fue posible guardar."); if (response.ok) await load(); };
  const title = labels[section] ?? "registro";
  const submit = async (event: FormEvent<HTMLElement>) => { event.preventDefault(); const form = event.target as HTMLFormElement; const data: Record<string, unknown> = Object.fromEntries(new FormData(form)); if (section === "commissions") { data.sellerPercentage = Number(data.sellerPercentage); data.companyPercentage = Number(data.companyPercentage); } if (section === "appointments" && typeof data.startsAt === "string") data.startsAt = new Date(data.startsAt).toISOString(); await send(`/api/${form.dataset.endpoint ?? api}`, data); form.reset(); };
  return <section className="operations-console" onSubmitCapture={submit}><div className="operations-toolbar"><p>{loading ? "Actualizando datos…" : `${items.length} ${title}${items.length === 1 ? "" : "s"} registrado${items.length === 1 ? "" : "s"}`}</p><button type="button" onClick={load}><RefreshCw size={15}/> Actualizar</button></div>
    {section === "inventory" && <InventoryForm owners={owners} send={send}/>} {section === "clients" && <ClientForm send={send}/>} {section === "appointments" && <AppointmentForm properties={properties} leads={leads} send={send}/>} {section === "offers" && <OfferForm properties={properties} leads={leads} send={send}/>} {section === "deals" && <DealForm properties={properties} leads={leads} send={send}/>} {section === "commissions" && <CommissionForm properties={properties} send={send}/>} 
    {notice && <p className="form-success" role="status">{notice}</p>}<div className="operations-list">{items.length ? items.map((item) => <article key={String(item.id)}><strong>{String(item.title ?? item.fullName ?? item.propertyId ?? "Registro")}</strong><span>{String(item.code ?? item.stage ?? item.status ?? (item.sellerPercentage ? `${item.sellerPercentage ?? ""}% asesor · ${item.companyPercentage ?? ""}% empresa` : item.startsAt ?? ""))}</span></article>) : <p className="muted-empty">Aún no hay registros. Usa el formulario para crear el primero.</p>}</div></section>;
}

function FormShell({ title, endpoint, children }: { title: string; endpoint?: string; children: React.ReactNode }) { return <form className="operation-form" data-endpoint={endpoint}><h2>{title}</h2>{children}</form>; }
function Submit({ children }: { children: string }) { return <button type="submit"><Plus size={16}/>{children}</button>; }
function InventoryForm({ owners }: { owners: Item[]; send: (p:string, d:Record<string,unknown>)=>Promise<void> }) { const [ownerId, setOwnerId] = useState(""); return <div className="operation-grid"><FormShell title="Nuevo propietario" endpoint="owners"><label>Nombre o razón social<input name="legalName" required placeholder="Ej. Ana Torres"/></label><label>Correo<input name="email" type="email" placeholder="ana@correo.com"/></label><label>Teléfono<input name="phone" placeholder="300 000 0000"/></label><Submit>Crear propietario</Submit></FormShell><FormShell title="Captar propiedad" endpoint="properties"><label>Propietario<select name="ownerId" value={ownerId} onChange={e=>setOwnerId(e.target.value)} required><option value="">Selecciona un propietario</option>{owners.map(o=><option key={String(o.id)} value={String(o.id)}>{String(o.legalName)}</option>)}</select></label><label>Código<input name="code" required placeholder="NT-24099"/></label><label>Título<input name="title" required placeholder="Apartamento luminoso"/></label><label>Ciudad<input name="city" required placeholder="Bogotá"/></label><label>Barrio<input name="neighborhood" required placeholder="Chicó"/></label><label>Dirección<input name="address" required placeholder="Calle 90 # 10-20"/></label><label>Tipo<input name="propertyType" required placeholder="Apartamento"/></label><label>Precio de venta<input name="salePrice" inputMode="decimal" required placeholder="1250000000"/></label><Submit>Crear propiedad</Submit></FormShell></div>; }
function ClientForm({ send }: { send:(p:string,d:Record<string,unknown>)=>Promise<void> }) { return <FormShell title="Registrar cliente"><label>Nombre completo<input name="fullName" required/></label><label>Teléfono<input name="phone" required inputMode="tel"/></label><label>Correo<input name="email" type="email"/></label><label>Origen<input name="source" defaultValue="MANUAL"/></label><Submit>Crear cliente</Submit></FormShell>; }
function Selects({ properties, leads }: { properties:Item[]; leads:Item[] }) { return <><label>Propiedad<select name="propertyId" required><option value="">Selecciona una propiedad</option>{properties.map(p=><option key={String(p.id)} value={String(p.id)}>{String(p.code)} · {String(p.title)}</option>)}</select></label><label>Cliente<select name="leadId" required><option value="">Selecciona un cliente</option>{leads.map(l=><option key={String(l.id)} value={String(l.id)}>{String(l.fullName)}</option>)}</select></label></>; }
function AppointmentForm({ properties, leads }: { properties:Item[]; leads:Item[]; send:(p:string,d:Record<string,unknown>)=>Promise<void> }) { return <FormShell title="Programar visita"><Selects properties={properties} leads={leads}/><label>Fecha y hora<input name="startsAt" type="datetime-local" required/></label><Submit>Programar visita</Submit></FormShell>; }
function OfferForm({ properties, leads }: { properties:Item[]; leads:Item[]; send:(p:string,d:Record<string,unknown>)=>Promise<void> }) { return <FormShell title="Crear oferta"><Selects properties={properties} leads={leads}/><label>Valor<input name="amount" inputMode="decimal" required placeholder="1200000000"/></label><label>Moneda<select name="currency" defaultValue="COP"><option>COP</option><option>USD</option></select></label><Submit>Enviar oferta</Submit></FormShell>; }
function DealForm({ properties, leads }: { properties:Item[]; leads:Item[]; send:(p:string,d:Record<string,unknown>)=>Promise<void> }) { return <FormShell title="Abrir operación"><Selects properties={properties} leads={leads}/><p>Solo se habilitan operaciones cuando existe una oferta aceptada para este cliente e inmueble.</p><Submit>Crear operación</Submit></FormShell>; }
function CommissionForm({ properties }: { properties:Item[]; send:(p:string,d:Record<string,unknown>)=>Promise<void> }) { return <FormShell title="Nueva regla de comisión"><label>Propiedad<select name="propertyId" required><option value="">Selecciona una propiedad</option>{properties.map(p=><option key={String(p.id)} value={String(p.id)}>{String(p.code)} · {String(p.title)}</option>)}</select></label><label>Porcentaje asesor<input name="sellerPercentage" type="number" min="0" max="100" step="0.01" required/></label><label>Porcentaje empresa<input name="companyPercentage" type="number" min="0" max="100" step="0.01" required/></label><Submit>Guardar regla</Submit></FormShell>; }
